[tools]
# programming languages and runtime tools
deno = "latest"
go = "latest"
java = "temurin-21"
node = "lts"
perl = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

# package managers
uv = "latest"

# linters and formatters
actionlint = "latest"
gofumpt = "latest"
golangci-lint	= "latest"
shellcheck = "latest"
staticcheck = "latest"

# database tools
duckdb = "latest"
mysql = "latest"
sqlite = "latest"

# editors and command line utils
vim = "latest"
pnpm = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.python]
uv_venv_auto = true
